    DROP TABLE EMPLOYEES;
    Drop table TRANSACTIONS;
    
    CREATE TABLE EMPLOYEES(
    NAME_ VARCHAR(20) PRIMARY KEY,
    EMP_ID INTEGER,
    MANAGER_ VARCHAR(4),
    PASSWORD_ VARCHAR(20)
    );
    
    CREATE TABLE TRANSACTIONS(
    NAME_ VARCHAR(15),
     EMP_ID INTEGER,
    RE_AMOUNT INTEGER,
    STATUS VARCHAR(10)
    );
    
    
    
ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_TRANSACTIONS_NAME
FOREIGN KEY (NAME_) REFERENCES EMPLOYEES(NAME_);
    
DROP SEQUENCE REIMBURSEMENTS_SEQUENCE;
/
CREATE SEQUENCE REIMBURSEMENTS_SEQUENCE
MINVALUE 1
MAXVALUE 1000
START WITH 1
INCREMENT BY 1;
/

    
INSERT INTO EMPLOYEES(EMP_ID, NAME_, MANAGER_, PASSWORD_)
VALUES (21,'Bankole','Y','Shadow26');

INSERT INTO EMPLOYEES(EMP_ID, NAME_, MANAGER_, PASSWORD_)
VALUES ( 23,'Bankelise','N','Sonic26');
INSERT INTO EMPLOYEES(EMP_ID, NAME_, MANAGER_, PASSWORD_)
VALUES ( 24,'Cerberus','N','Tails26');
INSERT INTO EMPLOYEES(EMP_ID, NAME_, MANAGER_, PASSWORD_)
VALUES ( 25,'Phoenix','N','Knuckles26');
INSERT INTO EMPLOYEES(EMP_ID, NAME_, MANAGER_, PASSWORD_)
VALUES ( 63,'Solari','N','Eggman26');

INSERT INTO TRANSACTIONS(NAME_,EMP_ID,RE_AMOUNT, STATUS)
VALUES ('Bankelise',23,1000,'Approved');

INSERT INTO TRANSACTIONS(NAME_,EMP_ID,RE_AMOUNT, STATUS)
VALUES ( 'Cerberus',24,3050,'Pending');
commit;